#!/bin/bash

PREFIX="${PREFIX:-/usr/local}"
SPOTLET_MOUNT_DIR="${SPOTLET_MOUNT_DIR:-$(pwd)}"
SPOTLET_GIT_REMOTE="${SPOTLET_GIT_REMOTE:-"git@github.com:"}"
SPOTLET_REMOTE="${SPOTLET_REMOTE:-"https://raw.githubusercontent.com"}"
SPOTLET_INDEX="${SPOTLET_INDEX:-${PREFIX}/spotlets}"

## https://gist.github.com/pkuczynski/8665367
parse_yaml() {
  local prefix=$2
  local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
  sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
    -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
  awk -F$fs '{
  indent = length($1)/2;
  vname[indent] = $2;
  for (i in vname) {if (i > indent) {delete vname[i]}}
    if (length($3) > 0) {
      vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
      printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
    }
  }'
}

spotlet-mount () {
  local path="${1}"
  local cid="${path}/run.cid"
  local args=()

  shift

  ## proxy args
  args+=("${@}")

  if ! test -d "${path}"; then
    echo >&2 "error: No such mount point \`${path}'"
    exit 1
  fi

  if test -f "$(pwd)/$(basename ${path}).cid"; then
    docker stop $(cat "$(pwd)/$(basename ${path}).cid") > /dev/null 2>&1
    rm -f "$(pwd)/$(basename ${path}).cid"
  fi

  ## volumes
  args+=("-v ${SPOTLET_MOUNT_DIR}:/usr/local/spotlet")
  args+=("-v ${path}:/usr/local/spotlet/service/app")

  ## tag
  args+=("-t service")

  ## command
  args+=("bash -c '/usr/local/spotlet/bin/spotlet-mount-init'")
  if test -f "${cid}"; then
    docker stop $(cat "${cid}") > /dev/null 2>&1
    rm -f "${cid}"
  fi

  #docker run ${args[@]} > "${path}/run.cid"
  docker run ${args[@]}
  return $?
}

package () {
  local path="${1}"
  local prefix="${2}"
  local pkg="${path}/spin.yml"

  if ! test -f "${pkg}"; then
    echo >&2 "error: Missing \`spin.yml'"
  fi

  (parse_yaml "${path}/spin.yml" | grep -ni "^${prefix}")

  return $?
}

install_spin () {
  local root="${1}"
  local spin="${2}"
  local remote="${SPOTLET_GIT_REMOTE}${spin}.git"
  local dest="${path}/spins/$(basename ${spin})"
  mkdir -p "${path}/spins"
  if ! test -d "${dest}"; then
    echo "install: spin (\`${spin}')"
    git clone "${remote}" "${dest}" > /dev/null 2>&1
  fi
  return $?
}

main () {
  local path="${1}"

  shift

  if ! test -d "${path}"; then
    local tmp="${SPOTLET_INDEX}/${path}"
    if test -d "${tmp}"; then
      path="${tmp}"
    else
      echo >&2 "error: No such mount point \`${path}'"
      return 1
    fi
  fi

  ## install spins
  package "${path}" 'spin' | {
    while read -r spin; do
      spin="$(echo ${spin} | tr '=' ' ' | awk '{print $2}' | tr -d '"')"
      install_spin "${path}" "${spin}" > /dev/null
      if (( $? != 0 )); then
        echo >&2 "error: Error installing \`${spin}'"
        exit 1
      fi
    done
  }

  if (( $? != 0 )); then
    return 1;
  fi

  ## mount
  spotlet-mount "${path}" "${@}"
  return $?
}

(main "${@}")
exit $?

