#!/usr/bin/env bash

if (( 0 == ${1} )); then
  echo
  echo "Successfully built Spotlet..."
  echo
  echo "     PREFIX = ${PREFIX}"
  echo "    SPOTLET = ${SPOTLET}"
  echo "    SERVICE = ${SERVICE}"
  echo "        APP = ${APP}"
  echo
fi

